
on:
  pull_request:
    branches: [ develop ]
    types: [opened]

jobs:
  tes_responsive_job:
    runs-on: ubuntu-latest
    name: Responsive Job
    steps:
      # Test repo code
      - name: Checkout pythton-responsive-test repo
        uses: actions/checkout@v2
        with:
          repository: IEXE-Tec/iextec-responsive-test
          ref: develop-action-test
          token: ${{ secrets.TOKEN_RESPONSIVE_TEST }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: to-responsive-test
      # - name: Verify paths
      #   shell: bash
      #   run: ./verify_path.sh
      - name: Responsive Test
        uses: ./ # Uses an action in the root directory
        id: responsive-test
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
      # - name: Configure AWS credentials from Test account
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Copy report after test
      #   run: |
      #     now=$(date +"%m_%d_%Y") && \
      #     aws s3 cp ./test_responsive/report.html s3://iexetec-test-reports/$GITHUB_REPOSITORY/$(date +"%m_%d_%Y")/
